### ISSUE TITLE
Leadscrew Locknut

### ISSUE THREAD

**Issue by S1L3NTANG3L** [CNCKitchen/Open-Pull#7]
I am unable to find the locknut for the leadscrews as per the design file. Is it custom made or does someone have a link for me where I can purchase it.

**Comment by PigeonFX** [comment]
Do you mean the 2x Trapezoidal Nut 10x2? 

If so, 98% sure these are the ones I ordered. 

https://www.ebay.co.uk/itm/273030924681

**Comment by S1L3NTANG3L** [comment]
A lovely thank you very much!

**Comment by S1L3NTANG3L** [comment]
So that seller doesn't ship to me :'( Do you think it would work if I just use the brass ones and machine the flange off?

**Comment by CNCKitchen** [comment]
Should definitely work as well and might even be cheaper. You might even get around to printing one out of PLA, depending on the loads you expect.

**Comment by S1L3NTANG3L** [comment]
I'm printing all the plastic parts from PETG but yeah I was scared about the two lock nuts, I'll try the brass method and post back here if it works. I don't see reason why they won't, as the moving head uses them(In your video) and they didn't strip out so I'm hopeful.
